[profile.default]
libs = ["lib"]
out = "out"
remappings = [
  "solmate/=lib/solmate/src/",
]
src = "src"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 80
multiline_func_header = "params_first"
quote_style = "double"
tab_width = 4
wrap_comments = false
